  List bestitems = [
      {
      "fav" : "0",  
      "itemid": "1238",
      "image": "images/electoronc/laptop1.png",
      "title": "HP Pav Aero Laptop ",
      "subtitle": "CPU: Ryzen 7-7735U, 16GB LPDDR5 on-board Graphics Card: AMD Radeon Integrated Graphics, VRAM: Shared, Display: 13.3 WUXGA (1920x1200) 400 nits IPS, 1TB, Windows 11",
      "price": 44350,
      "dis":"CPU: Ryzen 7-773...",
      "id":0,
      "tag":"lapn5",
      "avelablecolor": ["Red","Black"],
      "starsnum":2,
    },
    {
      "fav" : "0",
      "itemid": "1234",
      "image": "images/electoronc/tablet.png",
      "title": "Samsung Galaxy",
      "subtitle": "Ultra 5G Android Tablet, 14.6 inches display, 12GB RAM, 256GB Storage MicroSD Slot, S Pen Included, Beige -1 Year Warranty/Local Version",
      "price": 3500,
      "dis":"Ultra 5G Android...",
      "id":0,
      "tag":"lapt8",
      "avelablecolor": ["Black"],
      "starsnum":2,
    },
        {
      "fav" : "0",
      "itemid": "12374",
      "image": "images/food/drink.png",
      "title": "Fanta Orange Soft Drink",
      "subtitle": "Ingredients: CO2 saturated water, cane sugar, HFCS, natural and synthetic orange flavor, acidity regulator (330), synthetic sweetener (sucralose, acesulfame potassium),",
      "price": 6350,
      "dis":"Ingredients: CO2...",
      "id":1,
      "tag":"laps7",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },
        {
      "fav" : "0",
      "itemid": "12377",
      "image": "images/food/meal1.png",
      "title": "Spicy salmon bite rice",
      "subtitle": "Transform salmon fillets into these spicy gochujang salmon bite bowls in no time. The perfect healthy lunch or dinner.Each serving provides 327 kcal, 19.9g protein, 34.4g carbohydrate (of which 2.4g sugars), 11.8g fat (of which 2.1g saturates), 1.4g fibre and 1.3g salt",
      "price": 6350,
      "dis":"Transform salmon...",
      "id":1,
      "tag":"laps9",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },
  ];
List itemsoffers = [
      {
      "fav" : "1",    
      "itemid": "123",
      "image": "images/electoronc/laptop.png",
      "title": "DELL G15 Gaming Laptop  ",
      "subtitle": " 13th Intel Core i7-13650HX 14 Cores, NVIDIA GeForce RTX 3050 6GB GDDR6 Graphics, 16GB DDR5-4800 MHz RAM, 512GB SSD, 15.6 FHD (1920x1080) 120Hz, 4Z RGB Backlit, Ubuntu",
      "price": 8350,
      "dis":"13th Intel Core...",
      "id":0,
      "tag":"lapp9",
      "avelablecolor": ["Red","Black","Green"],
      "starsnum":5,
    },
    {
      "fav" : "0",
      "itemid": "1235",
      "image": "images/electoronc/phone.png",
      "title": "Redmi14C ",
      "subtitle": "Blue MediaTek Helio G81-Ultra | 50MP AI dual camera 6.88-inch 5160mAh battery 150% volume boost | 18 month manufacturer warranty",
      "price": 3555,
      "dis":"Blue MediaTek...",
      "id":0,
      "tag":"lape9",
      "avelablecolor": ["Red"],
      "starsnum":4,
    },
            {
      "fav" : "0",
      "itemid": "12375",
      "image": "images/food/drink1.png",
      "title": "Schweppes Soda Can",
      "subtitle": "Ingredients: CO2 saturated water, Acidity regulator (500(ii))",
      "price": 6350,
      "dis":"Ingredients: CO2..",
      "id":1,
      "tag":"laps0",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },
        {
      "fav" : "0",
      "itemid": "12377",
      "image": "images/food/meal1.png",
      "title": "Spicy salmon bite rice ",
      "subtitle": "Transform salmon fillets into these spicy gochujang salmon bite bowls in no time. The perfect healthy lunch or dinner.Each serving provides 327 kcal, 19.9g protein, 34.4g carbohydrate (of which 2.4g sugars), 11.8g fat (of which 2.1g saturates), 1.4g fibre and 1.3g salt",
      "price": 6350,
      "dis":"Transform salmon...",
      "id":1,
      "tag":"lapso",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },
    
{
      "fav" : "0",
      "itemid": "12dvsv375k",
      "image": "images/clothes/shose.png",
      "title": " Ankle Boot",
      "subtitle": "ICE CLUB Women's Casual Leather Comfy Ankle Boot",
      "price": 1200,
      "dis":"ICE CLUB..",
      "id":4,
      "tag":"abfcbymuym",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },                       
  ];
  List allproducts = [
    // electoroncs
      {
      "fav" : "1",    
      "itemid": "123",
      "image": "images/electoronc/laptop.png",
      "title": "DELL G15 Gaming Laptop",
      "subtitle": " 13th Intel Core i7-13650HX 14 Cores, NVIDIA GeForce RTX 3050 6GB GDDR6 Graphics, 16GB DDR5-4800 MHz RAM, 512GB SSD, 15.6 FHD (1920x1080) 120Hz, 4Z RGB Backlit, Ubuntu",
      "price": 8350,
      "dis":"13th Intel..",
      "id":0,
      "tag":"lapp",
      "avelablecolor": ["Red","Black","Green"],
      "starsnum":5,
    },
      {
      "fav" : "0",  
      "itemid": "1238",
      "image": "images/electoronc/laptop1.png",
      "title": "HP Pav Aero Laptop ",
      "subtitle": "CPU: Ryzen 7-7735U, 16GB LPDDR5 on-board Graphics Card: AMD Radeon Integrated Graphics, VRAM: Shared, Display: 13.3 WUXGA (1920x1200) 400 nits IPS, 1TB, Windows 11",
      "price": 44350,
      "dis":"CPU: Ryzen...",
      "id":0,
      "tag":"lapn",
      "avelablecolor": ["Red","Black"],
      "starsnum":2,
    },
    {
      "fav" : "0",
      "itemid": "1237",
      "image": "images/electoronc/lg.png",
      "title": "LG 55 Inch UHD UT80 4K ",
      "subtitle": "Smart TV AI Magic remote HDR10 webOS24-55UT80006LB (2024)",
      "price": 6350,
      "dis":"Smart TV AI...",
      "id":0,
      "tag":"laps",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },
    {
      "fav" : "0",
      "itemid": "1236",
      "image": "images/electoronc/pc.png",
      "title": "HP EliteDesk 705 G1 ",
      "subtitle": " SFF - A10 PRO-7800B 3.5 GHz - 8 GB - 500 GB",
      "price": 5550,
      "dis":" SFF - A10...",
      "id":0,
      "tag":"lapw",
      "avelablecolor": ["Red","Green"],
      "starsnum":1,
    },
    {
      "fav" : "0",
      "itemid": "1235",
      "image": "images/electoronc/phone.png",
      "title": "Redmi14C ",
      "subtitle": "Blue MediaTek Helio G81-Ultra | 50MP AI dual camera 6.88-inch 5160mAh battery 150% volume boost | 18 month manufacturer warranty",
      "price": 3555,
      "dis":"Blue MediaTek...",
      "id":0,
      "tag":"lape",
      "avelablecolor": ["Red"],
      "starsnum":4,
    },
    {
      "fav" : "0",
      "itemid": "1234",
      "image": "images/electoronc/tablet.png",
      "title": "Samsung Galaxy",
      "subtitle": "Ultra 5G Android Tablet, 14.6 inches display, 12GB RAM, 256GB Storage MicroSD Slot, S Pen Included, Beige -1 Year Warranty/Local Version",
      "price": 3500,
      "dis":"Ultra 5G Andr...",
      "id":0,
      "tag":"lapt",
      "avelablecolor": ["Black"],
      "starsnum":2,
    },



    // food
        {
      "fav" : "0",
      "itemid": "12370",
      "image": "images/food/food2.png",
      "title": "LG 55 Inch UHD UT80 4K ",
      "subtitle": "Transform salmon fillets into these spicy gochujang salmon bite bowls in no time. The perfect healthy lunch or dinner.Each serving provides 327 kcal, 19.9g protein, 34.4g carbohydrate (of which 2.4g sugars), 11.8g fat (of which 2.1g saturates), 1.4g fibre and 1.3g salt",
      "price": 6350,
      "dis":"Transform sa...",
      "id":1,
      "tag":"lapsl",
      "avelablecolor": [],
      "starsnum":3,
    },
        {
      "fav" : "0",
      "itemid": "12371",
      "image": "images/food/meal.png",
      "title": "Spicy salmon bite rice",
      "subtitle": "Transform salmon fillets into these spicy gochujang salmon bite bowls in no time. The perfect healthy lunch or dinner.Each serving provides 327 kcal, 19.9g protein, 34.4g carbohydrate (of which 2.4g sugars), 11.8g fat (of which 2.1g saturates), 1.4g fibre and 1.3g salt",
      "price": 6350,
      "dis":"Transform sa..",
      "id":1,
      "tag":"lapsh",
      "avelablecolor": [],
      "starsnum":3,
    },
        {
      "fav" : "0",
      "itemid": "12377",
      "image": "images/food/meal1.png",
      "title": "Spicy salmon bite rice",
      "subtitle": "Transform salmon fillets into these spicy gochujang salmon bite bowls in no time. The perfect healthy lunch or dinner.Each serving provides 327 kcal, 19.9g protein, 34.4g carbohydrate (of which 2.4g sugars), 11.8g fat (of which 2.1g saturates), 1.4g fibre and 1.3g salt",
      "price": 6350,
      "dis":"Transform..",
      "id":1,
      "tag":"lapsf",
      "avelablecolor": [],
      "starsnum":3,
    },
        {
      "fav" : "0",
      "itemid": "12374",
      "image": "images/food/drink.png",
      "title": "Fanta Orange Soft Drink",
      "subtitle": "– 320ml,Ingredients: CO2 saturated water, cane sugar, HFCS, natural and synthetic orange flavor, acidity regulator (330), synthetic sweetener (sucralose, acesulfame potassium),",
      "price": 6350,
      "dis":"Ingredients:",
      "id":1,
      "tag":"lapsd",
      "avelablecolor": [],
      "starsnum":3,
    },
            {
      "fav" : "0",
      "itemid": "12375",
      "image": "images/food/drink1.png",
      "title": "Schweppes Soda Can  ",
      "subtitle": "– 320ml,Ingredients: CO2 saturated water, Acidity regulator (500(ii))",
      "price": 6350,
      "dis":"Ingredients:",
      "id":1,
      "tag":"lapse",
      "avelablecolor": [],
      "starsnum":3,
    },

    // accessorise
                {
      "fav" : "0",
      "itemid": "12375asdd",
      "image": "images/accessorise/access1.png",
      "title": "Viromy Dainty Butterfly ",
      "subtitle": "Necklace for Women 18K Gold Plated Minimalist Cubic Zirconia Butterfly",
      "price": 5275,
      "dis":"Necklace for....",
      "id":2,
      "tag":"lapseddddd",
      "avelablecolor": ["Black"],
      "starsnum":3,
    },
                {
      "fav" : "0",
      "itemid": "12375fvcz",
      "image": "images/accessorise/access2.png",
      "title": "Palestine Map Charm Bracelet ",
      "subtitle": "Stainless Steel Palestine Map Palestine Flag Design for All Ages Unisex",
      "price": 727,
      "dis":"Stainless Steel...",
      "id":2,
      "tag":"lapseqqqqddd",
      "avelablecolor": ["Black","Green"],
      "starsnum":5,
    },
                {
      "fav" : "0",
      "itemid": "12375fvxv",
      "image": "images/accessorise/bag.png",
      "title": "Hand And Shoulder Bag  ",
      "subtitle": "Crocodile With Prefect Design - Black",
      "price": 2544,
      "dis":"Crocodile...",
      "id":2,
      "tag":"lapsewwwwwwwww",
      "avelablecolor": ["Black","Green"],
      "starsnum":2,
    },
                {
      "fav" : "0",
      "itemid": "12375ny",
      "image": "images/accessorise/ring.png",
      "title": "Unisex Dolphin Ring, ",
      "subtitle": "Silver",
      "price": 6350,
      "dis":"Silver..",
      "id":2,
      "tag":"lapsewwwwww",
      "avelablecolor": ["Silver"],
      "starsnum":1,
    },
                {
      "fav" : "0",
      "itemid": "12375k",
      "image": "images/accessorise/watch.png",
      "title": "HUAWEI Watch GT4",
      "subtitle": " 46mm Smartwatch, Upto 2-Weeks Battery Life",
      "price": 1000,
      "dis":"Ingredients:",
      "id":2,
      "tag":"lapseqqqq",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },

    //future
                    {
      "fav" : "0",
      "itemid": "12375kvdf",
      "image": "images/future/chair.png",
      "title": "Comfort Eco Chair",
      "subtitle": "A practical office chair that combines the comfort you need with an elegant look, you will sit in complete comfort because the chair made of high resilience foam provides great comfort that lasts for years.e",
      "price": 4650 ,
      "dis":"Ingredients:",
      "id":3,
      "tag":"eqqqq",
      "avelablecolor": ["Black","Green"],
      "starsnum":1,
    },
                        {
      "fav" : "0",
      "itemid": "1sdsv",
      "image": "images/future/fur.png",
      "title": "Sofa ",
      "subtitle": "Golden Life Sofa 80x75x160 cm - Beige",
      "price": 1000,
      "dis":"Golden Life...",
      "id":3,
      "tag":"apseqqqq",
      "avelablecolor": ["Black","Green"],
      "starsnum":4,
    },
                        {
      "fav" : "0",
      "itemid": "12sdvvs",
      "image": "images/future/fur1.png",
      "title": "swing",
      "subtitle": "Rattan swing chair with pillows, 100 x 210 x 105 cm",
      "price": 1000,
      "dis":"Ingredients:",
      "id":3,
      "tag":"lapseqqqq4",
      "avelablecolor": ["red","Black","Green"],
      "starsnum":5,
    },
                        {
      "fav" : "0",
      "itemid": "12dvsdvs5k",
      "image": "images/future/fur2.png",
      "title": "Chic Workstation",
      "subtitle": "Workspace Cafe Workstation Practical Desk (White)",
      "price": 1000,
      "dis":"Workspace Cafe..",
      "id":3,
      "tag":"lapseqqqq3",
      "avelablecolor": ["Black","Green"],
      "starsnum":1,
    },
                        {
      "fav" : "0",
      "itemid": "svddvs375k",
      "image": "images/future/fur3.png",
      "title":  "double bed",
      "subtitle": " 100 x 210 x 105 cm,combines the comfort you need with an elegant look, you will sleep in complete comfort because the bed made of high resilience foam provides great comfort that lasts for years.e",
      "price": 1000,
      "dis":"Ingredients:",
      "id":3,
      "tag":"lapseqqqq2",
      "avelablecolor": ["Red","Black","Green"],
      "starsnum":3,
    },

    ////clothes
                            {
      "fav" : "0",
      "itemid": "1237dsv5k",
      "image": "images/clothes/jacket.png",
      "title": "Jacket",
      "subtitle": "Mens Gogh Quilted Jacket",
      "price": 1614,
      "dis":"Mens Gogh..",
      "id":4,
      "tag":"lapseqqqq3eeee",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },                        {
      "fav" : "0",
      "itemid": "12sdv375k",
      "image": "images/clothes/shirt1.png",
      "title": "Sweatshirt",
      "subtitle": "Printonline Unisex Zip Hoodie Sweatshirt",
      "price": 61363,
      "dis":"Printonline Un..",
      "id":4,
      "tag":"lapseqqqq3rr",
      "avelablecolor": ["Black","Green"],
      "starsnum":2,
    },                        {
      "fav" : "0",
      "itemid": "12svds75k",
      "image": "images/clothes/shirt2.png",
      "title": "Mobaco Shirt ",
      "subtitle": "Mobaco Men Regular Fit Oxford Shirt CEBE MHR",
      "price": 9551,
      "dis":"Mobaco Men..",
      "id":4,
      "tag":"antenfb",
      "avelablecolor": ["Black","Green"],
      "starsnum":4,
    },                        {
      "fav" : "0",
      "itemid": "12dvsv375k",
      "image": "images/clothes/shose.png",
      "title": " Ankle Boot",
      "subtitle": "ICE CLUB Women's Casual Leather Comfy Ankle Boot",
      "price": 1200,
      "dis":"ICE CLUB..",
      "id":4,
      "tag":"abfcbymuym",
      "avelablecolor": ["Black","Green"],
      "starsnum":3,
    },                       
     {
      "fav" : "0",
      "itemid": "dsvsdvd",
      "image": "images/clothes/shose2.png",
      "title": "Casual Sneaker",
      "subtitle": " Testa Toro Casual Sneaker for Daily Life - Testa Toro, 41 EU",
      "price": 100,
      "dis":"Testa Toro..",
      "id":4,
      "tag":"lapseqqqasbfaq3uuuuu",
      "avelablecolor": ["Black","Green"],
      "starsnum":5,
    },


    //medicine 
         {
      "fav" : "0",
      "itemid": "avavaxw2sdv",
      "image": "images/medicine/medicine1.png",
      "title": "Nourish British",
      "subtitle": " Advanced Exfoliates & Hydrate Serum Advanced Lactic Acid 10% Serum +HA 30ml",
      "price": 422,
      "dis":" Advanced Exfolia..",
      "id":5,
      "tag":"lapseqqqabfafbq3uuuuu",
      "avelablecolor": ["Black","Green"],
      "starsnum":5,
    },
             {
      "fav" : "0",
      "itemid": "abafbsfba",
      "image": "images/medicine/medicine2.png",
      "title": "MONDO ",
      "subtitle": "Macro MONDO CREAM 50GM",
      "price": 424,
      "dis":"Macro....",
      "id":5,
      "tag":"abdsbs",
      "avelablecolor": ["Black","Green"],
      "starsnum":5,
    },
             {
      "fav" : "0",
      "itemid": "avavasdvxw2",
      "image": "images/medicine/medicine3.png",
      "title": "Omeprazole Delayed",
      "subtitle": "Basic Care Omeprazole Delayed Release Tablets 20 Mg, 28 Count (Packaging may vary) ",
      "price": 234,
      "dis":"Basic Care...",
      "id":5,
      "tag":"svdavw",
      "avelablecolor": ["Black","Green"],
      "starsnum":5,
    },
             {
      "fav" : "0",
      "itemid": "sava",
      "image": "images/medicine/medicine4.png",
      "title": "Laboratory Tested",
      "subtitle": " 222 MG | 120 Count | 99% Pure",
      "price": 1200,
      "dis":"222 MG...",
      "id":5,
      "tag":"sdvvsdb",
      "avelablecolor": ["Black","Green"],
      "starsnum":5,
    },


    // MAKEUP
                 {
      "fav" : "0",
      "itemid": "savasdvav",
      "image": "images/MAKEUP/make1.png",
      "title": "Maybelline",
      "subtitle": " Maybelline New York Fit Me Matte + Poreless - 122 CREAMY BEIGE",
      "price": 1200,
      "dis":"New York...",
      "id":6,
      "tag":"sdvvabasfbsdb",
      "avelablecolor": ["Black","Green"],
      "starsnum":2,
    },
                     {
      "fav" : "0",
      "itemid": "savafbabfa",
      "image": "images/MAKEUP/make2.png",
      "title": "Sheglam BAKED",
      "subtitle": "Sheglam BAKED GLOW SETTING POWDER NO.LIGHT PINK ",
      "price": 1200,
      "dis":"GLOW SET...",
      "id":6,
      "tag":"ababfaba",
      "avelablecolor": ["Black","Green"],
      "starsnum":5,
    },
                     {
      "fav" : "0",
      "itemid": "savabfasba",
      "image": "images/MAKEUP/make3.png",
      "title": "Eyeshadow Professional",
      "subtitle": "Menow New Eyeshadow Professional Palette - 16 Colors ",
      "price": 1200,
      "dis":"Menow New...",
      "id":6,
      "tag":"sdvvgdnsdb",
      "avelablecolor": ["Black","Green"],
      "starsnum":1,
    },
                     {
      "fav" : "0",
      "itemid": "savdhnfghdga",
      "image": "images/MAKEUP/make4.png",
      "title": "Amanda Milano",
      "subtitle": "Amanda Milano Butter Lipstick 06 ",
      "price": 1200,
      "dis":"Amanda Milano...",
      "id":6,
      "tag":"fbssfdbs",
      "avelablecolor": ["Green"],
      "starsnum":5,
    },
                     {
      "fav" : "0",
      "itemid": "savabsfxda",
      "image": "images/MAKEUP/make5.png",
      "title": "Bag",
      "subtitle": "Make Up Organizer Bag, Black ",
      "price": 1200,
      "dis":"Make Up...",
      "id":6,
      "tag":"sbdffb",
      "avelablecolor": ["Black",],
      "starsnum":4,
    },



    //office 
                         {
      "fav" : "0",
      "itemid": "sdvsdv",
      "image": "images/office/table.png",
      "title": "laptop table",
      "subtitle": "laptop table for bed reading",
      "price": 1240,
      "dis":"for bed ..",
      "id":7,
      "tag":"sbdqeff622fb",
      "avelablecolor": ["Red","Black","Green"],
      "starsnum":3,
    },
                             {
      "fav" : "0",
      "itemid": "sdvsdvwef56",
      "image": "images/office/tools.png",
      "title": "Pen Holder",
      "subtitle": "- Pen Cup - Metal Pen Holder - Mesh Pen Holder - Pen Holder for Desk - Pen Organizer for Desk",
      "price": 54000,
      "dis":"Pen Cup...",
      "id":7,
      "tag":"sbdf62q2fb",
      "avelablecolor": ["Red","Black","Green"],
      "starsnum":2,
    },
                             {
      "fav" : "0",
      "itemid": "sdvsethbrdv56",
      "image": "images/office/tools2.png",
      "title": "CHAIR Generic",
      "subtitle": " Faux Leather, Polyurethane, fabric, Plastic, Metal",
      "price": 1200,
      "dis":"Faux Leather...",
      "id":7,
      "tag":"sbdf6dsde22fb",
      "avelablecolor": ["Black","Green"],
      "starsnum":1,
    },
                             {
      "fav" : "0",
      "itemid": "sdvsefdsvdv56",
      "image": "images/office/tool1.png",
      "title": "Desk Lamp",
      "subtitle": "Reading Desk Lamp",
      "price": 3552,
      "dis":"Reading...",
      "id":7,
      "tag":"sbdferb622fb",
      "avelablecolor": ["Red","Black"],
      "starsnum":5,
    },
                             {
      "fav" : "0",
      "itemid": "sdvntedbsdv56",
      "image": "images/office/tools3.png",
      "title": "Madesa Home Office ",
      "subtitle": "Computer Writing Desk with 3 Drawers, 1 Door and 1 Storage Shelf, Plenty of Space, Wood, 45 D x 136 W x 77 H cm - White",
      "price": 1520,
      "dis":"Computer Wr...",
      "id":7,
      "tag":"rwbne",
      "avelablecolor": ["Black","Green"],
      "starsnum":4,
    },
  ];